name: Build Master & Publish

on:
  push:
    branches:
      - master

jobs:
  build-master:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version to env
        run: echo "VERSION=$(echo ${{steps.release_drafter.outputs.tag_name}})" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit

      - name: Make sure gradlew is executable
        run: "chmod +x ./gradlew"

      - name: Gradle (Build)
        run: "./gradlew build"

      - name: Upload artifacts (Main JAR)
        id: upload-main-jar
        uses: actions/upload-artifact@v4
        with:
          name: Main JAR
          path: build/libs/*-all.jar

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v4
        with:
          name: JARs
          path: build/libs/*.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          outputs: |
            type=local,dest=.

      - name: Upload Assets to Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }}
          asset_path: build/libs/*-all.jar
          github_token: ${{ secrets.GITHUB_TOKEN }}
